### ISSUE TITLE
Androidx incompatibility with other libraries

### ISSUE THREAD

**Issue by altherat** [trevorwang/flutter-zxing#7]
I'm getting a compilation error when trying to use this library with [file_picker](https://github.com/miguelpruivo/plugins_flutter_file_picker) or [open_file](https://github.com/crazecoder/open_file).

pubspec.yaml:
```
name: example
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fzxing: ^0.3.0
  file_picker: ^1.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  assets:
    - assets/
  uses-material-design: true
```

Error:
```
D8: Program type already present: android.support.v4.os.ResultReceiver$1

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: ...list of files...
  Program type already present: android.support.v4.os.ResultReceiver$1
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Gradle task assembleDebug failed with exit code 1
```
